# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='meals',
            field=models.CharField(choices=[('mealpack', 'Full Meal Plan'), ('dinnerday2', 'Second Day Dinner Only')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='session1',
            field=models.CharField(choices=[('Workshop A', 'Microsoft Powerpoint'), ('Workshop B', 'Microsoft Excel'), ('Workshop C', 'Microsoft Word')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='session2',
            field=models.CharField(choices=[('Workshop D', 'Email Etiquette'), ('Workshop E', 'One-on-one Meeting Etiquette'), ('Workshop F', 'Presentation Etiquette')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='session3',
            field=models.CharField(choices=[('Workshop G', 'Team Building'), ('Workshop H', 'Strategies to Improve Focus'), ('Workshop I', 'Effective Communication')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=5),
        ),
    ]
