# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('session', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('roomnumber', models.CharField(max_length=10)),
                ('starttime', models.CharField(max_length=10)),
                ('endtime', models.CharField(max_length=10)),
            ],
        ),
    ]
